apiVersion: skaffold/v4beta8
kind: Config
metadata:
  name: gcs-caching-proxy
build:
  artifacts:
    - image: gcs-handler
      context: cache-service/gcs-handler
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - kubernetes/gcs-handler/deployment.yml
    - kubernetes/gcs-handler/service.yml
    - kubernetes/nginx/config.yml
    - kubernetes/nginx/deployment.yml
    - kubernetes/nginx/service.yml
    - kubernetes/haproxy/config.yml
    - kubernetes/haproxy/deployment.yml
    - kubernetes/haproxy/service.yml  

portForward:
  - resourceType: service
    resourceName: haproxy-service
    namespace: default
    port: 80
    localPort: 8000
    address: localhost
