apiVersion: apps/v1
kind: Deployment
metadata:
  name: haproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: haproxy
  template:
    metadata:
      labels:
        app: haproxy
    spec:
      initContainers:
      - name: init-haproxy
        image: haproxy:latest
        command: ["sleep", "5"]
      containers:
      - name: haproxy
        image: haproxy:latest
        # command: ["tail", "-f", "/dev/null"]
        ports:
        - containerPort: 80
        volumeMounts:
        - name: haproxy-config-volume
          mountPath: /usr/local/etc/haproxy
      volumes:
      - name: haproxy-config-volume
        configMap:
          name: haproxy-config
